---
version: "3.8"

services:
  techmaturity:
    build: .
    ports:
      - "8080:3000"
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    depends_on: ["db"]
  db:
    image: postgres:11.7-alpine
    environment:
      - POSTGRES_DB=techmaturitydb
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
