default: &default
  feature_flags:
    tags: true
  feedback_slack:
    endpoint: "#endpoint"
    channel_name: "#channel_name"

development:
  <<: *default

test:
  <<: *default

production:
  feature_flags:
    tags: true
  feedback_slack:
    endpoint: "https://hooks.slack.com/services/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"
    channel_name: "#Techmaturity-feedback"
